language: java
node_js:
  - "0.10"

before_script:
  - cd www
  - npm install -g bower
  - npm install
  - bower install -f
  - cd ..

script: gradle build

notifications:
  email:
    recipients:
      - ajay.samgir@krishagni.com
    on_success: always
    on_failure: always


branches:
  only:
    - OS_v20_Travis_Setup
    
before_deploy:
  - export RELEASE_FILE=$(ls build/libs/*.war)
  - echo "Deploying $RELEASE_FILE to GitHub"
  
deploy:
  provider: releases
  api_key: "5GjWGappNRYWE3QEsjbS"
  file:
    - "${RELEASE_FILE}"
  skip_cleanup: true
  
  on:
    tags: true
    all_branches: true

