language: java
node_js:
- '0.10'
before_script:
- cd www
- npm install -g bower
- npm install
- bower install -f
- cd ..
script: gradle build
notifications:
  email:
    recipients:
    - ajay.samgir@krishagni.com
    on_success: always
    on_failure: always
branches:
  only:
  - OS_v20_Travis_Setup
before_deploy:
- export RELEASE_FILE=$(ls build/libs/*.war)
- echo "Deploying $RELEASE_FILE to GitHub"
deploy:
  provider: releases
  file:
  - ${RELEASE_FILE}
  skip_cleanup: true
  on:
    repo: asamgir/openspecimen
    all_branches: true
  api_key:
    secure: rG3rDvcLG4lUIU2lkyHela30rGu8HB1YtG6I3YbMoCIrI9EIRBYLgyGmirELEO7HBz++c1WZLWZixkkbOmF0vjLDl9TnvT8ChegjtF2DyNUwZcWhtVzgoOknA9DypJGwkTJrejszDUlddJC6rZDfjJK+UQWDqK23KhNLsSqZ5rsJ26Dks8++jGX4sIZ5tTKmhOzVC1kCgCPxGL50tduU4VZzQZ0/6H9x8oxtJIUhpEp/8MIW1eg3cFd/LAowY7F84LUs6T1cfmFQLOgDpsqMUS6Rd6MMC6zRkdQ2LigwKPlP+LiIn/uFjgDVEyLRymTFCNjnzkaHT5mGpXM7ky6VkuuFQnoUcZ0pVOcUXPUKz8IN1StKGcqr/a7L2yucPgC6WidqIxKL0v1dzB51TnwwVQ5Feaem1mpUvt9vLI5Ie6RAByLRVz6x5gP8AIm8CMKovDOUvjbepxGAdVlzEEM0tY7I5sppC0o6YUaY5hvOehU5JduXNkgG/UGPqlDMAFZkGTGkYb02KO5OsUhJ4DE65Kkaf9SKQQKo6QR6LyJ37JIWwElvs4jRbn0d3zUhtcdllZDW84WmjIGT4D/fsBnOS7s+88Qa6j/u/ATaYYcB2dzNV13x3PW/54YwSyEhcDWPjlO7se9f9yMd7zio3FFFuCQJNdQtuDqOjL97TwddG3o=
